common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.11.0

steps:
  - label: "Publish Simperium"
    command: |
      ./gradlew \
        :Simperium:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
        :Simperium:publish
    plugins: *common_plugins
